# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
#site_title: Geeker's 博客 | 基础·极致·分享
#title: Geeker's 博客 | 基础·极致·分享
title: Vimer.Me
#pTitle: Geeker's 博客 |
#articleTitle: Geeker's 博客
sTitle: 基础·极致·分享
#subtitle: — 技术、统计学、金融
subtitle: 基础·极致·分享
description: 行走于技术、创业之间
keywords: 大数据存储 | 互联网产品 | 设计 | 互联网创业 | 架构之美 | Objective-C | swift | javascript | vim | Emacs | C | nodejs | 操作系统 | 数据结构和算法 | golang
language: en
author: vimer.me
#email: emacs#vimer.org
#language: zh-CN
# 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://vimer.me
root: /
archive_dir: archives
category_dir: categories
code_dir: downloads/code
#permalink: articles/:title.html
permalink: :year/:month/:title/

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :year/:month/:title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
#server_ip: 192.168.1.54
logger: true
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Duoshuo
duoshuo_shortname: vimerme

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
#theme: hexo-theme-flat
#theme: hexo-theme-apollo
#theme: hexo-theme-aiki
#theme: modernist
#theme: tranquilpeak
theme: hvno
#theme: next
#theme: hexo-theme-mame
#theme: landscape
#theme: hueman
#theme: phase
#theme: hexo-theme-noderce
exclude_generator:

plugins: 
  - hexo-generator-feed
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap

sitemap:
    path: sitemap.xml

baidusitemap:
    path: baidusitemap.xml

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: github
  repository: git@github.com:vimer/vimer.github.com.git
  #repo:
    #github: git@github.com:vimer/vimer.github.com.git,master
#gitcafe: git@gitcafe.com:infogeeker/infogeeker.git,gitcafe-pages
